services:
  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: crawl4ai
    ports:
      - "11235:11235"
    shm_size: "1g"
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./output:/app/output

  webcrawler:
    build: .
    container_name: webcrawler
    ports:
      - "8888:8000"
    depends_on:
      - crawl4ai
    environment:
      - CRAWLER_CRAWL4AI_API=http://crawl4ai:11235
    volumes:
      - ./output:/app/output
      - ./data:/app/data
    restart: unless-stopped
